---
title: "Commentaires SPSA"
author: "Hubert Cadieux"
date: "2023-01-24"
output: pdf_document
---

# Sean Cain, main discussant du papier
* INTÉGRER Expliquer plus explicitement et plus en évidence l'objectif principal de ce papier. Donner un "bigger push" sur le focus du papier. Pourquoi volatilité niveau des ridings. Focus sur la volatilité
* INTÉGRER Élxn Québec 2022 est un cas plutôt précis, peut-être plus généralisé. Srm que le QC a l'espace idéologique le plus multidim en Am du Nord et qu'il a le plus de partis compétitifs. Ensuite élargir pour ouvrir sur d'autres cas (Canada). Pourquoi on s'attend à ce que ça fonctionne ailleurs aussi?
* INTÉGRER En dire plus sur le RCI, comment ça a été vérifié? Est-ce qu'il y a une différence entre un 6 et un 3? Est-ce qu'il y a des thresholds? Chaque parti est évalué indépendamment, donc utile peu importe le nb de partis. Plus développer
  - On pourrait mettre les prob prédites en annexe
* DROPPER Pour la mesure de volatilité pré-Campagne (donc la fragilité des circonscriptions), comparer à une mesure alternative (même chose pour pendant la campagne)
* INTÉGRER Moins de transformations (normalisation, scaling, etc.) --> Plutôt mieux justifier et expliquer les transformations, pt en bas de page pour les détails
* DROP Mieux mesurer la volatilité PENDANT la campagne (ne pas additionner les variances)


# Sean Kates
* DROP Ajouter des contrôles pour nationalisme/historique de la circonscription (puisque le shift idéologique est mentionné dans le contexte de l'article)


# William Poirier
* MRP: réduire le nombre de variables de la table postStrat
* Faire le MRP pour les régions, réarranger ENSUITE pour les ridings
* Changer le "volatility index" (avant la campagne) pour utiliser "fragilité" à la place
* Analyser les luttes à 2 au lieu d'additionner les 5 partis
* Comparer la fragilité du vote CAQ à la volatilité du vote CAQ pendant la campagne (refaire pour chaque parti)
* Faire du regression discontinuity
  - La fenêtre autour du début de la campagne